export const SEED_CAR_KEY_ORDER = [
  'id',
  'image',
  'class',
  'brand',
  'model',
  'normalizedKey',
  'status',
  'message',
  'sources',
  'rarity',
  'stars',
  'keyCar',
  'country',

  'epics',
  'obtainableVia',

  'stockRank',
  'stockTopSpeed',
  'stockAcceleration',
  'stockHandling',
  'stockNitro',

  'oneStarMaxRank',
  'oneStarMaxTopSpeed',
  'oneStarMaxAcceleration',
  'oneStarMaxHandling',
  'oneStarMaxNitro',

  'twoStarMaxRank',
  'twoStarMaxTopSpeed',
  'twoStarMaxAcceleration',
  'twoStarMaxHandling',
  'twoStarMaxNitro',

  'threeStarMaxRank',
  'threeStarMaxTopSpeed',
  'threeStarMaxAcceleration',
  'threeStarMaxHandling',
  'threeStarMaxNitro',

  'fourStarMaxRank',
  'fourStarMaxTopSpeed',
  'fourStarMaxAcceleration',
  'fourStarMaxHandling',
  'fourStarMaxNitro',

  'fiveStarMaxRank',
  'fiveStarMaxTopSpeed',
  'fiveStarMaxAcceleration',
  'fiveStarMaxHandling',
  'fiveStarMaxNitro',

  'sixStarMaxRank',
  'sixStarMaxTopSpeed',
  'sixStarMaxAcceleration',
  'sixStarMaxHandling',
  'sixStarMaxNitro',

  'goldMaxRank',
  'goldTopSpeed',
  'goldAcceleration',
  'goldHandling',
  'goldNitro',

  'added',
  'addedWith',
  'addedDate',
  'totalUpgradeCost',
  'totalGlPoints',

  'blueprints1Star',
  'blueprints2Star',
  'blueprints3Star',
  'blueprints4Star',
  'blueprints5Star',
  'blueprints6Star',
];