export const SEED_CAR_KEY_ORDER = [
  'Id',
  'Image',
  'Class',
  'Brand',
  'Model',
  'normalizedKey',
  'status',
  'message',
  'sources',
  'Rarity',
  'Stars',
  'KeyCar',
  'Country',

  'Epics',
  'ObtainableVia',

  'Stock_Rank',
  'Stock_Top_Speed',
  'Stock_Acceleration',
  'Stock_Handling',
  'Stock_Nitro',

  'One_Star_Max_Rank',
  'One_Star_Max_Top_Speed',
  'One_Star_Max_Acceleration',
  'One_Star_Max_Handling',
  'One_Star_Max_Nitro',

  'Two_Star_Max_Rank',
  'Two_Star_Max_Top_Speed',
  'Two_Star_Max_Acceleration',
  'Two_Star_Max_Handling',
  'Two_Star_Max_Nitro',

  'Three_Star_Max_Rank',
  'Three_Star_Max_Top_Speed',
  'Three_Star_Max_Acceleration',
  'Three_Star_Max_Handling',
  'Three_Star_Max_Nitro',

  'Four_Star_Max_Rank',
  'Four_Star_Max_Top_Speed',
  'Four_Star_Max_Acceleration',
  'Four_Star_Max_Handling',
  'Four_Star_Max_Nitro',

  'Five_Star_Max_Rank',
  'Five_Star_Max_Top_Speed',
  'Five_Star_Max_Acceleration',
  'Five_Star_Max_Handling',
  'Five_Star_Max_Nitro',

  'Six_Star_Max_Rank',
  'Six_Star_Max_Top_Speed',
  'Six_Star_Max_Acceleration',
  'Six_Star_Max_Handling',
  'Six_Star_Max_Nitro',

  'Gold_Max_Rank',
  'Gold_Top_Speed',
  'Gold_Acceleration',
  'Gold_Handling',
  'Gold_Nitro',

  'Added',
  'Added_With',
  'Added date',
  'Total upgrade cost',
  'Total GL points',

  'BPs_1_Star',
  'BPs_2_Star',
  'BPs_3_Star',
  'BPs_4_Star',
  'BPs_5_Star',
  'BPs_6_Star',
];