export const carData = [

    
    {
      Id: 56,
      Class: "C",
      Order: 68,
      Brand: "Vencer",
      Model: "Sarthe",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3638,
      Epics: 8,
      Obtainable_Via: "GL11 / Multiplayer",
      Garage_Lvl: 11,
      Top_Speed: "350,5",
      Acceleration: "74,12",
      Handling: "62,87",
      Nitro: "46,83",
      Nitro_TS: null,
      "Unnamed: 16": "364,5",
      Perfect_Nitro_TS: null,
      Added: "Road Kings",
      Added_With: null,
      "Added date": "30/01/2019",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "The Netherlands",
      Tags: "Europe",
      BPs_1_Star: "35",
      BPs_2_Star: 15,
      BPs_3_Star: 21,
      BPs_4_Star: 28,
      BPs_5_Star: 35,
      BPs_6_Star: null,
      Total_BPs: 134,
      "Unnamed: 32": 23638,
      "Cost epic": 6000,
    },
    {
      Id: 101,
      Class: "C",
      Order: 70,
      Brand: "Bentley Mulliner",
      Model: "Bacalar",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3665,
      Epics: 8,
      Obtainable_Via: null,
      Garage_Lvl: 47,
      Top_Speed: "340,4",
      Acceleration: "77,38",
      Handling: "67,26",
      Nitro: "55,85",
      Nitro_TS: null,
      "Unnamed: 16": "354,0",
      Perfect_Nitro_TS: null,
      Added: "British Season",
      Added_With: "LP car",
      "Added date": "27/08/2020",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "UK",
      Tags: "Europe",
      BPs_1_Star: "35",
      BPs_2_Star: 15,
      BPs_3_Star: 21,
      BPs_4_Star: 28,
      BPs_5_Star: 35,
      BPs_6_Star: null,
      Total_BPs: 134,
      "Unnamed: 32": 23665,
      "Cost epic": 0,
    },
    {
      Id: 246,
      Class: "C",
      Order: 71,
      Brand: "De Tomaso",
      Model: "P900",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3678,
      Epics: 8,
      Obtainable_Via: "Car Hunt",
      Garage_Lvl: null,
      Top_Speed: "335,2",
      Acceleration: "81,32",
      Handling: "60,44",
      Nitro: "59,52",
      Nitro_TS: null,
      "Unnamed: 16": "348,6",
      Perfect_Nitro_TS: null,
      Added: "Eurobloom",
      Added_With: "Car Hunt",
      "Added date": "17/04/2024",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: null,
      BPs_1_Star: "35",
      BPs_2_Star: 15,
      BPs_3_Star: 21,
      BPs_4_Star: 28,
      BPs_5_Star: 35,
      BPs_6_Star: null,
      Total_BPs: 134,
      "Unnamed: 32": 23678,
      "Cost epic": null,
    },
    
    {
      Id: 164,
      Class: "C",
      Order: 76,
      Brand: "Brabham",
      Model: "BT62",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3817,
      Epics: 8,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "322,0",
      Acceleration: "83,93",
      Handling: "76,11",
      Nitro: "75,70",
      Nitro_TS: null,
      "Unnamed: 16": "334,9",
      Perfect_Nitro_TS: null,
      Added: "New Breed Rivals",
      Added_With: "SE",
      "Added date": "04/04/2022",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Australia",
      Tags: null,
      BPs_1_Star: 0,
      BPs_2_Star: 25,
      BPs_3_Star: 32,
      BPs_4_Star: 36,
      BPs_5_Star: 41,
      BPs_6_Star: null,
      Total_BPs: 134,
      "Unnamed: 32": 23817,
      "Cost epic": 0,
    },
    {
      Id: 193,
      Class: "C",
      Order: 79,
      Brand: "Ares",
      Model: "S1",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3859,
      Epics: 8,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "307,8",
      Acceleration: "89,55",
      Handling: "78,93",
      Nitro: "68,93",
      Nitro_TS: null,
      "Unnamed: 16": "320,1",
      Perfect_Nitro_TS: "?",
      Added: "Winterfest",
      Added_With: "GP",
      "Added date": "12/12/2022",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: null,
      BPs_1_Star: 0,
      BPs_2_Star: 25,
      BPs_3_Star: 32,
      BPs_4_Star: 36,
      BPs_5_Star: 41,
      BPs_6_Star: null,
      Total_BPs: 134,
      "Unnamed: 32": 23859,
      "Cost epic": null,
    },
    {
      Id: 69,
      Class: "C",
      Order: 81,
      Brand: "Arrinera",
      Model: "Hussarya 33",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3897,
      Epics: 8,
      Obtainable_Via: "GL13",
      Garage_Lvl: 14,
      Top_Speed: "352,1",
      Acceleration: "78,53",
      Handling: "59,47",
      Nitro: "47,71",
      Nitro_TS: null,
      "Unnamed: 16": "366,2",
      Perfect_Nitro_TS: null,
      Added: "Tune It Up",
      Added_With: null,
      "Added date": "27/07/2019",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Poland",
      Tags: "Europe",
      BPs_1_Star: "35",
      BPs_2_Star: 15,
      BPs_3_Star: 21,
      BPs_4_Star: 28,
      BPs_5_Star: 35,
      BPs_6_Star: null,
      Total_BPs: 134,
      "Unnamed: 32": 23897,
      "Cost epic": 6000,
    },
    {
      Id: 22,
      Class: "B",
      Order: 91,
      Brand: "Jaguar",
      Model: "F-Type SVR",
      Rarity: "Rare",
      Stars: 4,
      Max_Rank: 2500,
      Epics: 8,
      Obtainable_Via: "GL05",
      Garage_Lvl: 5,
      Top_Speed: "341,0",
      Acceleration: "75,55",
      Handling: "49,28",
      Nitro: "50,12",
      Nitro_TS: null,
      "Unnamed: 16": "354,6",
      Perfect_Nitro_TS: null,
      Added: "Soft Launch",
      Added_With: null,
      "Added date": "26/02/2018",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "UK",
      Tags: "Europe",
      BPs_1_Star: "30",
      BPs_2_Star: 12,
      BPs_3_Star: 22,
      BPs_4_Star: 36,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 100,
      "Unnamed: 32": 32500,
      "Cost epic": 8000,
    },
    {
      Id: 202,
      Class: "B",
      Order: 92,
      Brand: "Ferrari",
      Model: "F50",
      Rarity: "Rare",
      Stars: 4,
      Max_Rank: 2576,
      Epics: 8,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "338,9",
      Acceleration: "73,85",
      Handling: "43,52",
      Nitro: "61,42",
      Nitro_TS: null,
      "Unnamed: 16": "352,5",
      Perfect_Nitro_TS: null,
      Added: "City of Lights",
      Added_With: "LP",
      "Added date": "06/02/2023",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: null,
      BPs_1_Star: "55",
      BPs_2_Star: 35,
      BPs_3_Star: 44,
      BPs_4_Star: 54,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 188,
      "Unnamed: 32": 32576,
      "Cost epic": null,
    },
    {
      Id: 23,
      Class: "B",
      Order: 93,
      Brand: "Exotic Rides",
      Model: "W70",
      Rarity: "Uncommon",
      Stars: 3,
      Max_Rank: 2633,
      Epics: 4,
      Obtainable_Via: "GL06",
      Garage_Lvl: 6,
      Top_Speed: "329,7",
      Acceleration: "80,21",
      Handling: "45,20",
      Nitro: "56,71",
      Nitro_TS: null,
      "Unnamed: 16": "342,9",
      Perfect_Nitro_TS: null,
      Added: "Soft Launch",
      Added_With: null,
      "Added date": "26/02/2018",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "USA",
      Tags: null,
      BPs_1_Star: "40",
      BPs_2_Star: 30,
      BPs_3_Star: 70,
      BPs_4_Star: null,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 140,
      "Unnamed: 32": 32633,
      "Cost epic": 8000,
    },
    
    {
      Id: 25,
      Class: "B",
      Order: 96,
      Brand: "Lamborghini",
      Model: "Asterion",
      Rarity: "Rare",
      Stars: 4,
      Max_Rank: 2983,
      Epics: 8,
      Obtainable_Via: "Daily Missions",
      Garage_Lvl: null,
      Top_Speed: "336,8",
      Acceleration: "81,05",
      Handling: "45,56",
      Nitro: "68,21",
      Nitro_TS: null,
      "Unnamed: 16": "350,3",
      Perfect_Nitro_TS: null,
      Added: "Soft Launch",
      Added_With: null,
      "Added date": "26/02/2018",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: "Europe; Super Car; Hybrid",
      BPs_1_Star: "40",
      BPs_2_Star: 12,
      BPs_3_Star: 24,
      BPs_4_Star: 36,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 112,
      "Unnamed: 32": 32983,
      "Cost epic": 8000,
    },
   
    {
      Id: 126,
      Class: "B",
      Order: 98,
      Brand: "Ferrari",
      Model: "Roma",
      Rarity: "Rare",
      Stars: 4,
      Max_Rank: 3069,
      Epics: 8,
      Obtainable_Via: "Car Hunt",
      Garage_Lvl: 22,
      Top_Speed: "331,7",
      Acceleration: "77,45",
      Handling: "60,49",
      Nitro: "66,78",
      Nitro_TS: null,
      "Unnamed: 16": "345,0",
      Perfect_Nitro_TS: null,
      Added: "Italian Season",
      Added_With: "Car Hunt",
      "Added date": "08/04/2021",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "USA",
      Tags: "Super Car",
      BPs_1_Star: "55",
      BPs_2_Star: 35,
      BPs_3_Star: 44,
      BPs_4_Star: 54,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 188,
      "Unnamed: 32": 33069,
      "Cost epic": 8000,
    },
    {
      Id: 151,
      Class: "B",
      Order: 99,
      Brand: "Arash",
      Model: "AF10",
      Rarity: "Rare",
      Stars: 4,
      Max_Rank: 3112,
      Epics: 8,
      Obtainable_Via: null,
      Garage_Lvl: 45,
      Top_Speed: "337,0",
      Acceleration: "78,73",
      Handling: "50,41",
      Nitro: "59,60",
      Nitro_TS: null,
      "Unnamed: 16": "350,5",
      Perfect_Nitro_TS: null,
      Added: "Festive Season",
      Added_With: "LP car",
      "Added date": "16/12/2021",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "UK",
      Tags: "Europe; Hybrid",
      BPs_1_Star: "55",
      BPs_2_Star: 35,
      BPs_3_Star: 44,
      BPs_4_Star: 54,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 188,
      "Unnamed: 32": 33112,
      "Cost epic": 0,
    },
    {
      Id: 26,
      Class: "B",
      Order: 101,
      Brand: "Cadillac",
      Model: "Cien Concept",
      Rarity: "Rare",
      Stars: 4,
      Max_Rank: 3155,
      Epics: 8,
      Obtainable_Via: "Exclusive",
      Garage_Lvl: null,
      Top_Speed: "368,0",
      Acceleration: "76,55",
      Handling: "36,14",
      Nitro: "61,10",
      Nitro_TS: null,
      "Unnamed: 16": "382,7",
      Perfect_Nitro_TS: null,
      Added: "Soft Launch",
      Added_With: null,
      "Added date": "26/02/2018",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "USA",
      Tags: "Super Car",
      BPs_1_Star: "40",
      BPs_2_Star: 18,
      BPs_3_Star: 22,
      BPs_4_Star: 36,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 116,
      "Unnamed: 32": 33155,
      "Cost epic": 8000,
    },
    {
      Id: 267,
      Class: "B",
      Order: 102,
      Brand: "Aston Martin",
      Model: "Valour",
      Rarity: "Rare",
      Stars: 4,
      Max_Rank: 3178,
      Epics: 8,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "331,0",
      Acceleration: "78,23",
      Handling: "56,43",
      Nitro: "60,73",
      Nitro_TS: null,
      "Unnamed: 16": null,
      Perfect_Nitro_TS: null,
      Added: "Speed Parade/Haunted Wheels",
      Added_With: "GP",
      "Added date": "23/9/2024",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "UK",
      Tags: null,
      BPs_1_Star: 0,
      BPs_2_Star: 35,
      BPs_3_Star: 55,
      BPs_4_Star: 85,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 175,
      "Unnamed: 32": 33178,
      "Cost epic": null,
    },
    {
      Id: 240,
      Class: "B",
      Order: 104,
      Brand: "Lamborghini",
      Model: "Huracán STO",
      Rarity: "Rare",
      Stars: 4,
      Max_Rank: 3222,
      Epics: 8,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "320,3",
      Acceleration: "85,88",
      Handling: "73,05",
      Nitro: "57,09",
      Nitro_TS: null,
      "Unnamed: 16": "333,1",
      Perfect_Nitro_TS: null,
      Added: "Italian Revolution I",
      Added_With: "LP car",
      "Added date": "19/2/2024",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: null,
      BPs_1_Star: "55",
      BPs_2_Star: 35,
      BPs_3_Star: 44,
      BPs_4_Star: 54,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 188,
      "Unnamed: 32": 33222,
      "Cost epic": null,
    },
    {
      Id: 79,
      Class: "B",
      Order: 105,
      Brand: "Italdesign",
      Model: "Zerouno",
      Rarity: "Rare",
      Stars: 4,
      Max_Rank: 3245,
      Epics: 8,
      Obtainable_Via: "GL08",
      Garage_Lvl: 8,
      Top_Speed: "341,0",
      Acceleration: "79,25",
      Handling: "58,34",
      Nitro: "54,10",
      Nitro_TS: null,
      "Unnamed: 16": "354,6",
      Perfect_Nitro_TS: null,
      Added: "Godly Beasts",
      Added_With: "DS",
      "Added date": "10/12/2019",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: "Europe",
      BPs_1_Star: "40",
      BPs_2_Star: 35,
      BPs_3_Star: 44,
      BPs_4_Star: 54,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 173,
      "Unnamed: 32": 33245,
      "Cost epic": 8000,
    },
    {
      Id: 165,
      Class: "B",
      Order: 107,
      Brand: "Arash",
      Model: "AF8 Falcon Edition",
      Rarity: "Rare",
      Stars: 4,
      Max_Rank: 3289,
      Epics: 8,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "332,6",
      Acceleration: "76,74",
      Handling: "66,01",
      Nitro: "76,94",
      Nitro_TS: null,
      "Unnamed: 16": "345,9",
      Perfect_Nitro_TS: null,
      Added: "New Breed Rivals",
      Added_With: "Looper Prix",
      "Added date": "04/04/2022",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "UK",
      Tags: "Europe",
      BPs_1_Star: 0,
      BPs_2_Star: 35,
      BPs_3_Star: 55,
      BPs_4_Star: 85,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 175,
      "Unnamed: 32": 33289,
      "Cost epic": 0,
    },
    {
      Id: 27,
      Class: "B",
      Order: 108,
      Brand: "Ferrari",
      Model: "488 GTB",
      Rarity: "Rare",
      Stars: 4,
      Max_Rank: 3334,
      Epics: 8,
      Obtainable_Via: "GL08",
      Garage_Lvl: 8,
      Top_Speed: "347,6",
      Acceleration: "80,24",
      Handling: "48,38",
      Nitro: "65,84",
      Nitro_TS: null,
      "Unnamed: 16": "361,5",
      Perfect_Nitro_TS: null,
      Added: "Soft Launch",
      Added_With: null,
      "Added date": "26/02/2018",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: "Europe; Super Car",
      BPs_1_Star: "40",
      BPs_2_Star: 12,
      BPs_3_Star: 22,
      BPs_4_Star: 36,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 110,
      "Unnamed: 32": 33334,
      "Cost epic": 8000,
    },
    {
      Id: 208,
      Class: "B",
      Order: 109,
      Brand: "Kepler",
      Model: "Motion",
      Rarity: "Rare",
      Stars: 4,
      Max_Rank: 3380,
      Epics: 8,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "338,5",
      Acceleration: "85,45",
      Handling: "48,72",
      Nitro: "61,18",
      Nitro_TS: null,
      "Unnamed: 16": "352,0",
      Perfect_Nitro_TS: null,
      Added: "European Season (2023)",
      Added_With: null,
      "Added date": "30/03/2023",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "USA",
      Tags: null,
      BPs_1_Star: "55",
      BPs_2_Star: 35,
      BPs_3_Star: 44,
      BPs_4_Star: 54,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 188,
      "Unnamed: 32": 33380,
      "Cost epic": null,
    },
    {
      Id: 146,
      Class: "B",
      Order: 110,
      Brand: "Drako",
      Model: "GTE",
      Rarity: "Rare",
      Stars: 4,
      Max_Rank: 3425,
      Epics: 8,
      Obtainable_Via: "Car Hunt",
      Garage_Lvl: 25,
      Top_Speed: "346,2",
      Acceleration: "81,85",
      Handling: "47,31",
      Nitro: "61,18",
      Nitro_TS: null,
      "Unnamed: 16": "360,0",
      Perfect_Nitro_TS: null,
      Added: "Electric Season",
      Added_With: "Car Hunt",
      "Added date": "23/09/2021",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "USA",
      Tags: "Electric; Super Car",
      BPs_1_Star: "40",
      BPs_2_Star: 12,
      BPs_3_Star: 22,
      BPs_4_Star: 36,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 110,
      "Unnamed: 32": 33425,
      "Cost epic": 8000,
    },
    {
      Id: 28,
      Class: "B",
      Order: 111,
      Brand: "Glickenhaus",
      Model: "003S",
      Rarity: "Rare",
      Stars: 4,
      Max_Rank: 3519,
      Epics: 8,
      Obtainable_Via: "GL10 / Multiplayer",
      Garage_Lvl: 10,
      Top_Speed: "368,8",
      Acceleration: "79,44",
      Handling: "38,58",
      Nitro: "63,11",
      Nitro_TS: null,
      "Unnamed: 16": "383,6",
      Perfect_Nitro_TS: null,
      Added: "Soft Launch",
      Added_With: null,
      "Added date": "26/02/2018",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "USA",
      Tags: null,
      BPs_1_Star: "40",
      BPs_2_Star: 12,
      BPs_3_Star: 22,
      BPs_4_Star: 36,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 110,
      "Unnamed: 32": 33519,
      "Cost epic": 8000,
    },
    
    {
      Id: 251,
      Class: "B",
      Order: 113,
      Brand: "Aston Martin",
      Model: "DB12",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3580,
      Epics: 8,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "343,2",
      Acceleration: "74,11",
      Handling: "69,68",
      Nitro: "77,89",
      Nitro_TS: null,
      "Unnamed: 16": "356,9",
      Perfect_Nitro_TS: null,
      Added: "Supercharged Summer",
      Added_With: "LP car",
      "Added date": "27/5/2024",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "UK",
      Tags: null,
      BPs_1_Star: "45",
      BPs_2_Star: 17,
      BPs_3_Star: 23,
      BPs_4_Star: 32,
      BPs_5_Star: 45,
      BPs_6_Star: null,
      Total_BPs: 162,
      "Unnamed: 32": 33580,
      "Cost epic": null,
    },
    {
      Id: 187,
      Class: "B",
      Order: 114,
      Brand: "Nissan",
      Model: "R390 GT1",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3627,
      Epics: 8,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "373,5",
      Acceleration: "76,72",
      Handling: "52,63",
      Nitro: "55,45",
      Nitro_TS: null,
      "Unnamed: 16": "388,4",
      Perfect_Nitro_TS: null,
      Added: "Around the World",
      Added_With: "GP",
      "Added date": "03/04/2022",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Japan",
      Tags: null,
      BPs_1_Star: 0,
      BPs_2_Star: 26,
      BPs_3_Star: 34,
      BPs_4_Star: 40,
      BPs_5_Star: 62,
      BPs_6_Star: null,
      Total_BPs: 162,
      "Unnamed: 32": 33627,
      "Cost epic": 0,
    },
    {
      Id: 29,
      Class: "B",
      Order: 115,
      Brand: "Ferrari",
      Model: "F12tdf",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3724,
      Epics: 8,
      Obtainable_Via: "GL12",
      Garage_Lvl: 13,
      Top_Speed: "360,5",
      Acceleration: "78,38",
      Handling: "40,13",
      Nitro: "80,18",
      Nitro_TS: null,
      "Unnamed: 16": "374,9",
      Perfect_Nitro_TS: null,
      Added: "Soft Launch",
      Added_With: null,
      "Added date": "26/02/2018",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: "Europe; Super Car",
      BPs_1_Star: "30",
      BPs_2_Star: 9,
      BPs_3_Star: 13,
      BPs_4_Star: 21,
      BPs_5_Star: 32,
      BPs_6_Star: null,
      Total_BPs: 105,
      "Unnamed: 32": 33724,
      "Cost epic": 8000,
    },
    {
      Id: 227,
      Class: "B",
      Order: 116,
      Brand: "Maserati",
      Model: "MC20",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3773,
      Epics: 8,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "335,7",
      Acceleration: "81,63",
      Handling: "90,79",
      Nitro: "75,84",
      Nitro_TS: null,
      "Unnamed: 16": "349,1",
      Perfect_Nitro_TS: null,
      Added: "Black Friday (2023)",
      Added_With: "LP",
      "Added date": "25/09/2023",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: null,
      BPs_1_Star: "45",
      BPs_2_Star: 17,
      BPs_3_Star: 23,
      BPs_4_Star: 32,
      BPs_5_Star: 45,
      BPs_6_Star: null,
      Total_BPs: 162,
      "Unnamed: 32": 33773,
      "Cost epic": null,
    },
    {
      Id: 127,
      Class: "B",
      Order: 117,
      Brand: "Lamborghini",
      Model: "Murciélago LP 640 Roadster",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3792,
      Epics: 8,
      Obtainable_Via: null,
      Garage_Lvl: 27,
      Top_Speed: "354,1",
      Acceleration: "77,54",
      Handling: "67,18",
      Nitro: "61,13",
      Nitro_TS: null,
      "Unnamed: 16": "368,3",
      Perfect_Nitro_TS: null,
      Added: "Italian Season",
      Added_With: "LP car",
      "Added date": "08/04/2021",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: "Europe; Super Car",
      BPs_1_Star: "45",
      BPs_2_Star: 17,
      BPs_3_Star: 23,
      BPs_4_Star: 32,
      BPs_5_Star: 45,
      BPs_6_Star: null,
      Total_BPs: 162,
      "Unnamed: 32": 33792,
      "Cost epic": 0,
    },
    
    {
      Id: 30,
      Class: "B",
      Order: 119,
      Brand: "Chevrolet",
      Model: "Corvette Grand Sport",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3921,
      Epics: 8,
      Obtainable_Via: "GL13",
      Garage_Lvl: 13,
      Top_Speed: "331,2",
      Acceleration: "76,55",
      Handling: "92,99",
      Nitro: "80,87",
      Nitro_TS: null,
      "Unnamed: 16": "344,4",
      Perfect_Nitro_TS: null,
      Added: "Soft Launch",
      Added_With: null,
      "Added date": "26/02/2018",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "USA",
      Tags: null,
      BPs_1_Star: "30",
      BPs_2_Star: 9,
      BPs_3_Star: 13,
      BPs_4_Star: 21,
      BPs_5_Star: 32,
      BPs_6_Star: null,
      Total_BPs: 105,
      "Unnamed: 32": 33921,
      "Cost epic": 8000,
    },
    {
      Id: 70,
      Class: "B",
      Order: 120,
      Brand: "Aston Martin",
      Model: "Vantage GT12",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3946,
      Epics: 8,
      Obtainable_Via: "GL14",
      Garage_Lvl: 15,
      Top_Speed: "337,8",
      Acceleration: "78,26",
      Handling: "86,85",
      Nitro: "80,46",
      Nitro_TS: null,
      "Unnamed: 16": "351,3",
      Perfect_Nitro_TS: null,
      Added: "Tune It Up",
      Added_With: null,
      "Added date": "27/07/2019",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "UK",
      Tags: "Europe",
      BPs_1_Star: "45",
      BPs_2_Star: 17,
      BPs_3_Star: 23,
      BPs_4_Star: 32,
      BPs_5_Star: 45,
      BPs_6_Star: null,
      Total_BPs: 162,
      "Unnamed: 32": 33946,
      "Cost epic": 8000,
    },
    {
      Id: 102,
      Class: "B",
      Order: 120,
      Brand: "Apex",
      Model: "AP-0",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3946,
      Epics: 8,
      Obtainable_Via: "Car Hunt",
      Garage_Lvl: 28,
      Top_Speed: "335,1",
      Acceleration: "80,96",
      Handling: "89,37",
      Nitro: "75,16",
      Nitro_TS: null,
      "Unnamed: 16": "348,5",
      Perfect_Nitro_TS: "358,0",
      Added: "British Season",
      Added_With: "Car Hunt",
      "Added date": "27/08/2020",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "UK",
      Tags: "Electric; Europe",
      BPs_1_Star: "45",
      BPs_2_Star: 17,
      BPs_3_Star: 23,
      BPs_4_Star: 32,
      BPs_5_Star: 45,
      BPs_6_Star: null,
      Total_BPs: 162,
      "Unnamed: 32": 33946,
      "Cost epic": 8000,
    },
    {
      Id: 114,
      Class: "B",
      Order: 122,
      Brand: "Apollo",
      Model: "IE",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3953,
      Epics: 8,
      Obtainable_Via: "Car Hunt",
      Garage_Lvl: 46,
      Top_Speed: "348,3",
      Acceleration: "84,65",
      Handling: "73,17",
      Nitro: "69,12",
      Nitro_TS: null,
      "Unnamed: 16": "362,2",
      Perfect_Nitro_TS: null,
      Added: "Full Throttle",
      Added_With: "LP car",
      "Added date": "10/12/2020",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Germany",
      Tags: "Europe; Super Car",
      BPs_1_Star: "45",
      BPs_2_Star: 17,
      BPs_3_Star: 23,
      BPs_4_Star: 32,
      BPs_5_Star: 45,
      BPs_6_Star: null,
      Total_BPs: 162,
      "Unnamed: 32": 33953,
      "Cost epic": 8000,
    },
    {
      Id: 54,
      Class: "B",
      Order: 123,
      Brand: "SIN",
      Model: "R1 550",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3971,
      Epics: 8,
      Obtainable_Via: "TC",
      Garage_Lvl: 27,
      Top_Speed: "370,6",
      Acceleration: "77,04",
      Handling: "45,74",
      Nitro: "85,00",
      Nitro_TS: null,
      "Unnamed: 16": "385,4",
      Perfect_Nitro_TS: null,
      Added: "Slipstream",
      Added_With: null,
      "Added date": "11/12/2018",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Bulgary",
      Tags: "Europe",
      BPs_1_Star: "30",
      BPs_2_Star: 9,
      BPs_3_Star: 13,
      BPs_4_Star: 21,
      BPs_5_Star: 32,
      BPs_6_Star: null,
      Total_BPs: 105,
      "Unnamed: 32": 33971,
      "Cost epic": 8000,
    },
    {
      Id: 166,
      Class: "B",
      Order: 134,
      Brand: "Puritalia",
      Model: "Berlinetta",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 4076,
      Epics: 8,
      Obtainable_Via: "Car Hunt",
      Garage_Lvl: 47,
      Top_Speed: "349,5",
      Acceleration: "83,43",
      Handling: "82,74",
      Nitro: "69,66",
      Nitro_TS: null,
      "Unnamed: 16": "363,5",
      Perfect_Nitro_TS: null,
      Added: "New Breed Rivals",
      Added_With: "LP car",
      "Added date": "04/04/2022",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: "Europe; Hybrid",
      BPs_1_Star: "45",
      BPs_2_Star: 17,
      BPs_3_Star: 23,
      BPs_4_Star: 32,
      BPs_5_Star: 45,
      BPs_6_Star: null,
      Total_BPs: 162,
      "Unnamed: 32": 34076,
      "Cost epic": 0,
    },
    
    {
      Id: 233,
      Class: "B",
      Order: 136,
      Brand: "Lamborghini",
      Model: "Invencible",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 4091,
      Epics: 8,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "340,4",
      Acceleration: "88,49",
      Handling: "75,74",
      Nitro: "67,94",
      Nitro_TS: null,
      "Unnamed: 16": "354,0",
      Perfect_Nitro_TS: null,
      Added: "Festive Sparks",
      Added_With: "LP car",
      "Added date": "11/12/2023",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: null,
      BPs_1_Star: "45",
      BPs_2_Star: 17,
      BPs_3_Star: 23,
      BPs_4_Star: 32,
      BPs_5_Star: 45,
      BPs_6_Star: null,
      Total_BPs: 162,
      "Unnamed: 32": 34091,
      "Cost epic": null,
    },
    {
      Id: 59,
      Class: "B",
      Order: 137,
      Brand: "Lamborghini",
      Model: "Huracán EVO Spyder",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 4109,
      Epics: 8,
      Obtainable_Via: "GL16",
      Garage_Lvl: 18,
      Top_Speed: "344,0",
      Acceleration: "84,31",
      Handling: "75,97",
      Nitro: "82,43",
      Nitro_TS: null,
      "Unnamed: 16": "357,8",
      Perfect_Nitro_TS: null,
      Added: "Motor Show",
      Added_With: "SE",
      "Added date": "04/03/2019",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: "Europe; Super Car",
      BPs_1_Star: "45",
      BPs_2_Star: 17,
      BPs_3_Star: 23,
      BPs_4_Star: 32,
      BPs_5_Star: 45,
      BPs_6_Star: null,
      Total_BPs: 162,
      "Unnamed: 32": 34109,
      "Cost epic": 8000,
    },
    {
      Id: 152,
      Class: "B",
      Order: 139,
      Brand: "Nissan",
      Model: "GT-R50 Italdesign",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 4153,
      Epics: 8,
      Obtainable_Via: null,
      Garage_Lvl: 30,
      Top_Speed: "349,5",
      Acceleration: "86,36",
      Handling: "73,86",
      Nitro: "64,59",
      Nitro_TS: null,
      "Unnamed: 16": "363,5",
      Perfect_Nitro_TS: null,
      Added: "Festive Season",
      Added_With: "DS",
      "Added date": "16/12/2021",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Japan",
      Tags: "Asia",
      BPs_1_Star: "45",
      BPs_2_Star: 17,
      BPs_3_Star: 23,
      BPs_4_Star: 32,
      BPs_5_Star: 45,
      BPs_6_Star: null,
      Total_BPs: 162,
      "Unnamed: 32": 34153,
      "Cost epic": 0,
    },
    {
      Id: 132,
      Class: "B",
      Order: 140,
      Brand: "Zenvo",
      Model: "TSR-S",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 4171,
      Epics: 8,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "342,4",
      Acceleration: "85,38",
      Handling: "82,88",
      Nitro: "67,36",
      Nitro_TS: null,
      "Unnamed: 16": "356,1",
      Perfect_Nitro_TS: "?",
      Added: "European Season",
      Added_With: "GP",
      "Added date": "01/06/2021",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Denmark",
      Tags: "Europe; Hybrid",
      BPs_1_Star: 0,
      BPs_2_Star: 26,
      BPs_3_Star: 34,
      BPs_4_Star: 40,
      BPs_5_Star: 62,
      BPs_6_Star: null,
      Total_BPs: 162,
      "Unnamed: 32": 34171,
      "Cost epic": 0,
    },
    {
      Id: 174,
      Class: "B",
      Order: 141,
      Brand: "Lamborghini",
      Model: "Sesto Elemento",
      Rarity: "Epic",
      Stars: 6,
      Max_Rank: 4183,
      Epics: 12,
      Obtainable_Via: null,
      Garage_Lvl: 52,
      Top_Speed: "346,5",
      Acceleration: "87,26",
      Handling: "70,27",
      Nitro: "74,76",
      Nitro_TS: null,
      "Unnamed: 16": "360,4",
      Perfect_Nitro_TS: null,
      Added: "Raging Bull Season",
      Added_With: null,
      "Added date": "30/05/2022",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: "Europe",
      BPs_1_Star: "55",
      BPs_2_Star: 18,
      BPs_3_Star: 24,
      BPs_4_Star: 32,
      BPs_5_Star: 47,
      BPs_6_Star: 50,
      Total_BPs: 226,
      "Unnamed: 32": 34183,
      "Cost epic": 0,
    },
    {
      Id: 179,
      Class: "B",
      Order: 143,
      Brand: "Security",
      Model: "Interceptor",
      Rarity: "Epic",
      Stars: 6,
      Max_Rank: 4265,
      Epics: null,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "361,5",
      Acceleration: "83,36",
      Handling: "79,15",
      Nitro: "45,82",
      Nitro_TS: null,
      "Unnamed: 16": "376,0",
      Perfect_Nitro_TS: null,
      Added: "Bring the Heat",
      Added_With: null,
      "Added date": "25/07/2022",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "USA",
      Tags: null,
      BPs_1_Star: "55",
      BPs_2_Star: 18,
      BPs_3_Star: 24,
      BPs_4_Star: 32,
      BPs_5_Star: 50,
      BPs_6_Star: 61,
      Total_BPs: 240,
      "Unnamed: 32": 34250,
      "Cost epic": 0,
    },
    
    {
      Id: 83,
      Class: "B",
      Order: 146,
      Brand: "Lotus",
      Model: "Evija",
      Rarity: "Epic",
      Stars: 6,
      Max_Rank: 4276,
      Epics: 12,
      Obtainable_Via: null,
      Garage_Lvl: 49,
      Top_Speed: "368,1",
      Acceleration: "81,14",
      Handling: "65,02",
      Nitro: "63,31",
      Nitro_TS: null,
      "Unnamed: 16": "382,8",
      Perfect_Nitro_TS: null,
      Added: "Grand Prix",
      Added_With: "SE",
      "Added date": "05/02/2020",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "UK",
      Tags: "Electric; Europe",
      BPs_1_Star: "55",
      BPs_2_Star: 18,
      BPs_3_Star: 24,
      BPs_4_Star: 32,
      BPs_5_Star: 50,
      BPs_6_Star: 61,
      Total_BPs: 240,
      "Unnamed: 32": 34276,
      "Cost epic": 0,
    },
    {
      Id: 259,
      Class: "B",
      Order: 147,
      Brand: "Lamborghini",
      Model: "Gallardo Security",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 4300,
      Epics: null,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: null,
      Acceleration: null,
      Handling: null,
      Nitro: null,
      Nitro_TS: null,
      "Unnamed: 16": null,
      Perfect_Nitro_TS: null,
      Added: "Unite Update",
      Added_With: null,
      "Added date": "16/7/2024",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: null,
      BPs_1_Star: null,
      BPs_2_Star: null,
      BPs_3_Star: null,
      BPs_4_Star: null,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: null,
      "Unnamed: 32": 34300,
      "Cost epic": null,
    },
    
    {
      Id: 133,
      Class: "B",
      Order: 149,
      Brand: "Volkswagen",
      Model: "W12 Coupé",
      Rarity: "Epic",
      Stars: 6,
      Max_Rank: 4348,
      Epics: 12,
      Obtainable_Via: "Showroom",
      Garage_Lvl: null,
      Top_Speed: "370,5",
      Acceleration: "79,08",
      Handling: "84,44",
      Nitro: "54,64",
      Nitro_TS: null,
      "Unnamed: 16": "385,3",
      Perfect_Nitro_TS: null,
      Added: "European Season",
      Added_With: "SE",
      "Added date": "01/06/2021",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Germany",
      Tags: "Europe",
      BPs_1_Star: 0,
      BPs_2_Star: 26,
      BPs_3_Star: 34,
      BPs_4_Star: 46,
      BPs_5_Star: 61,
      BPs_6_Star: 73,
      Total_BPs: 240,
      "Unnamed: 32": 34348,
      "Cost epic": 0,
    },
    
    {
      Id: 209,
      Class: "B",
      Order: 151,
      Brand: "Lamborghini",
      Model: "Revuelto",
      Rarity: "Epic",
      Stars: 6,
      Max_Rank: 4375,
      Epics: 12,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "361,5",
      Acceleration: "86,36",
      Handling: "76,33",
      Nitro: "54,22",
      Nitro_TS: null,
      "Unnamed: 16": "376,0",
      Perfect_Nitro_TS: null,
      Added: "European Season (2023)",
      Added_With: null,
      "Added date": "30/03/2023",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: null,
      BPs_1_Star: 0,
      BPs_2_Star: 26,
      BPs_3_Star: 34,
      BPs_4_Star: 46,
      BPs_5_Star: 61,
      BPs_6_Star: 73,
      Total_BPs: 240,
      "Unnamed: 32": 34375,
      "Cost epic": null,
    },
    {
      Id: 268,
      Class: "B",
      Order: 152,
      Brand: "Lamborghini",
      Model: "Temerario",
      Rarity: "Epic",
      Stars: 6,
      Max_Rank: 4398,
      Epics: 12,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "359,1",
      Acceleration: "87,26",
      Handling: "71,33",
      Nitro: "62,70",
      Nitro_TS: null,
      "Unnamed: 16": null,
      Perfect_Nitro_TS: null,
      Added: "Speed Parade/Haunted Wheels",
      Added_With: "SE",
      "Added date": "23/9/2024",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: null,
      BPs_1_Star: 0,
      BPs_2_Star: 26,
      BPs_3_Star: 34,
      BPs_4_Star: 46,
      BPs_5_Star: 61,
      BPs_6_Star: 73,
      Total_BPs: 240,
      "Unnamed: 32": 34398,
      "Cost epic": null,
    },
    {
      Id: 252,
      Class: "B",
      Order: 153,
      Brand: "Lotus",
      Model: "E-R9",
      Rarity: "Epic",
      Stars: 6,
      Max_Rank: 4403,
      Epics: 12,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "365,2",
      Acceleration: "87,44",
      Handling: "68,40",
      Nitro: "51,80",
      Nitro_TS: null,
      "Unnamed: 16": "379,8",
      Perfect_Nitro_TS: null,
      Added: "Supercharged Summer",
      Added_With: "SE",
      "Added date": "27/5/2024",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "UK",
      Tags: null,
      BPs_1_Star: 0,
      BPs_2_Star: 26,
      BPs_3_Star: 34,
      BPs_4_Star: 46,
      BPs_5_Star: 61,
      BPs_6_Star: 73,
      Total_BPs: 240,
      "Unnamed: 32": 34403,
      "Cost epic": null,
    },
    {
      Id: 121,
      Class: "A",
      Order: 156,
      Brand: "Nio",
      Model: "EP9",
      Rarity: "Rare",
      Stars: 4,
      Max_Rank: 3194,
      Epics: 8,
      Obtainable_Via: "Car Hunt",
      Garage_Lvl: 43,
      Top_Speed: "326,1",
      Acceleration: "83,03",
      Handling: "70,49",
      Nitro: "68,68",
      Nitro_TS: null,
      "Unnamed: 16": "339,1",
      Perfect_Nitro_TS: null,
      Added: "Fire and Lightning",
      Added_With: "LP car",
      "Added date": "03/02/2021",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "China",
      Tags: "Asia; Electric",
      BPs_1_Star: "60",
      BPs_2_Star: 40,
      BPs_3_Star: 51,
      BPs_4_Star: 63,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 214,
      "Unnamed: 32": 43194,
      "Cost epic": 10000,
    },
    {
      Id: 33,
      Class: "A",
      Order: 158,
      Brand: "Dodge",
      Model: "Viper GTS",
      Rarity: "Rare",
      Stars: 4,
      Max_Rank: 3306,
      Epics: 8,
      Obtainable_Via: "GL09",
      Garage_Lvl: 9,
      Top_Speed: "353,5",
      Acceleration: "80,33",
      Handling: "45,29",
      Nitro: "67,55",
      Nitro_TS: null,
      "Unnamed: 16": "367,6",
      Perfect_Nitro_TS: null,
      Added: "Soft Launch",
      Added_With: null,
      "Added date": "26/02/2018",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "USA",
      Tags: "Super Car",
      BPs_1_Star: "45",
      BPs_2_Star: 21,
      BPs_3_Star: 28,
      BPs_4_Star: 42,
      BPs_5_Star: null,
      BPs_6_Star: null,
      Total_BPs: 136,
      "Unnamed: 32": 43306,
      "Cost epic": 10000,
    },
    
    {
      Id: 36,
      Class: "A",
      Order: 163,
      Brand: "Lamborghini",
      Model: "Aventador SV Coupé",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3763,
      Epics: 12,
      Obtainable_Via: "GL12",
      Garage_Lvl: 12,
      Top_Speed: "367,9",
      Acceleration: "80,83",
      Handling: "50,15",
      Nitro: "70,60",
      Nitro_TS: null,
      "Unnamed: 16": "382,6",
      Perfect_Nitro_TS: null,
      Added: "Soft Launch",
      Added_With: null,
      "Added date": "26/02/2018",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Italy",
      Tags: "Europe; Hyper",
      BPs_1_Star: "35",
      BPs_2_Star: 12,
      BPs_3_Star: 15,
      BPs_4_Star: 24,
      BPs_5_Star: 36,
      BPs_6_Star: null,
      Total_BPs: 122,
      "Unnamed: 32": 43763,
      "Cost epic": 10000,
    },
    {
      Id: 253,
      Class: "A",
      Order: 164,
      Brand: "McMurtry",
      Model: "Spéirling",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3789,
      Epics: 12,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "331,7",
      Acceleration: "90,52",
      Handling: "80,62",
      Nitro: "61,70",
      Nitro_TS: null,
      "Unnamed: 16": "345,0",
      Perfect_Nitro_TS: null,
      Added: "Supercharged Summer",
      Added_With: "Unleashed",
      "Added date": "27/5/2024",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "Ireland",
      Tags: null,
      BPs_1_Star: "50",
      BPs_2_Star: 23,
      BPs_3_Star: 27,
      BPs_4_Star: 36,
      BPs_5_Star: 51,
      BPs_6_Star: null,
      Total_BPs: 187,
      "Unnamed: 32": 43789,
      "Cost epic": null,
    },
    
    {
      Id: 80,
      Class: "A",
      Order: 167,
      Brand: "Chevrolet",
      Model: "Corvette ZR1",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3876,
      Epics: 12,
      Obtainable_Via: null,
      Garage_Lvl: null,
      Top_Speed: "355,4",
      Acceleration: "82,03",
      Handling: "60,09",
      Nitro: "76,33",
      Nitro_TS: null,
      "Unnamed: 16": "369,6",
      Perfect_Nitro_TS: null,
      Added: "Godly Beasts",
      Added_With: "DS",
      "Added date": "10/12/2019",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "USA",
      Tags: null,
      BPs_1_Star: "50",
      BPs_2_Star: 23,
      BPs_3_Star: 27,
      BPs_4_Star: 36,
      BPs_5_Star: 51,
      BPs_6_Star: null,
      Total_BPs: 187,
      "Unnamed: 32": 43876,
      "Cost epic": 10000,
    },
    {
      Id: 103,
      Class: "A",
      Order: 168,
      Brand: "Jaguar",
      Model: "C-X75",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3898,
      Epics: 12,
      Obtainable_Via: null,
      Garage_Lvl: 50,
      Top_Speed: "369,2",
      Acceleration: "75,54",
      Handling: "73,17",
      Nitro: "74,12",
      Nitro_TS: null,
      "Unnamed: 16": "384,0",
      Perfect_Nitro_TS: null,
      Added: "British Season",
      Added_With: "Unleashed",
      "Added date": "27/08/2020",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "UK",
      Tags: "Europe",
      BPs_1_Star: "50",
      BPs_2_Star: 23,
      BPs_3_Star: 27,
      BPs_4_Star: 36,
      BPs_5_Star: 51,
      BPs_6_Star: null,
      Total_BPs: 187,
      "Unnamed: 32": 43898,
      "Cost epic": 0,
    },
    {
      Id: 37,
      Class: "A",
      Order: 169,
      Brand: "VLF",
      Model: "Force 1 V10",
      Rarity: "Epic",
      Stars: 5,
      Max_Rank: 3929,
      Epics: 12,
      Obtainable_Via: "Exclusive",
      Garage_Lvl: null,
      Top_Speed: "368,8",
      Acceleration: "80,33",
      Handling: "54,68",
      Nitro: "74,63",
      Nitro_TS: null,
      "Unnamed: 16": "383,6",
      Perfect_Nitro_TS: null,
      Added: "Soft Launch",
      Added_With: null,
      "Added date": "26/02/2018",
      "Total upgrade cost": null,
      "Total GL points": null,
      Country: "USA",
      Tags: "Hyper",
      BPs_1_Star: "45",
      BPs_2_Star: 12,
      BPs_3_Star: 15,
      BPs_4_Star: 24,
      BPs_5_Star: 36,
      BPs_6_Star: null,
      Total_BPs: 132,
      "Unnamed: 32": 43929,
      "Cost epic": 10000,
    },
  ];
